# ===== CONFIGURAÇÃO DO CODECOV =====
# Arquivo de configuração para integração com Codecov
# https://docs.codecov.io/docs/codecov-yaml

# ===== CONFIGURAÇÕES GERAIS =====
coverage:
  # Cobertura mínima global
  minimum: 80
  # Precisão das casas decimais
  precision: 2
  # Arredondamento
  round: down
  # Status de cobertura
  status:
    # Projeto principal
    project:
      # Cobertura mínima para o projeto
      target: 80%
      # Se deve falhar se não atingir o target
      threshold: 5%
    # Cobertura de patches (mudanças)
    patch:
      # Cobertura mínima para patches
      target: 80%
      # Se deve falhar se não atingir o target
      threshold: 5%

# ===== CONFIGURAÇÕES DE RELATÓRIO =====
comment:
  # Layout do comentário
  layout: 'reach, diff, flags, files'
  # Comportamento
  behavior: default
  # Requer aprovação
  require_changes: false

# ===== CONFIGURAÇÕES DE ARQUIVOS =====
ignore:
  # ===== ARQUIVOS DE TESTE =====
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/*.spec.ts'
  - '**/*.spec.tsx'
  - '**/__tests__/**'
  - '**/tests/**'
  - '**/test/**'
  - '**/tests/e2e/**'
  - '**/playwright-report/**'
  - '**/test-results/**'

  # ===== ARQUIVOS DE CONFIGURAÇÃO =====
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/next.config.js'
  - '**/tailwind.config.js'
  - '**/postcss.config.js'
  - '**/vitest.config.ts'
  - '**/playwright.config.ts'
  - '**/eslint.config.js'
  - '**/.eslintrc.*'
  - '**/.prettierrc.*'
  - '**/.releaserc.*'
  - '**/codecov.yml'
  - '**/lefthook.yml'
  - '**/.lintstagedrc.*'
  - '**/.editorconfig'

  # ===== ARQUIVOS DE BUILD =====
  - '**/.next/**'
  - '**/out/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/coverage/**'

  # ===== ARQUIVOS DE DOCUMENTAÇÃO =====
  - '**/*.md'
  - '**/*.mdx'
  - '**/docs/**'
  - '**/README.md'
  - '**/PACKAGE.md'
  - '**/CHANGELOG.md'

  # ===== ARQUIVOS DE TIPOS =====
  - '**/*.d.ts'
  - '**/next-env.d.ts'

  # ===== ARQUIVOS DE CONFIGURAÇÃO DO PROJETO =====
  - '**/package.json'
  - '**/package-lock.json'
  - '**/yarn.lock'
  - '**/pnpm-lock.yaml'
  - '**/.gitignore'
  - '**/.env*'
  - '**/tsconfig.json'
  - '**/jest.config.*'
  - '**/vite.config.*'

  # ===== ARQUIVOS DE CI/CD =====
  - '**/.github/**'
  - '**/.gitlab-ci.yml'
  - '**/azure-pipelines.yml'
  - '**/circle.yml'
  - '**/travis.yml'
  - '**/appveyor.yml'
  - '**/.github/workflows/**'

  # ===== ARQUIVOS DE DEPENDÊNCIAS =====
  - '**/node_modules/**'
  - '**/vendor/**'

  # ===== ARQUIVOS TEMPORÁRIOS =====
  - '**/*.tmp'
  - '**/*.temp'
  - '**/.tmp/**'
  - '**/.temp/**'

  # ===== ARQUIVOS DE CACHE =====
  - '**/.cache/**'

  # ===== ARQUIVOS DE LOGS =====
  - '**/*.log'
  - '**/logs/**'

  # ===== ARQUIVOS DE IDE =====
  - '**/.vscode/**'
  - '**/.idea/**'
  - '**/*.swp'
  - '**/*.swo'
  - '**/*~'

  # ===== ARQUIVOS DE SISTEMA =====
  - '**/.DS_Store'
  - '**/Thumbs.db'
  - '**/desktop.ini'

  # ===== ARQUIVOS DE STORYBOOK =====
  - '**/*.stories.ts'
  - '**/*.stories.tsx'
  - '**/.storybook/**'
  - '**/storybook-static/**'

  # ===== ARQUIVOS DE GERADORES =====
  - '**/generators/**'
  - '**/plopfile.js'

  # ===== ARQUIVOS DE SCRIPTS =====
  - '**/scripts/**'
  - '**/*.sh'

# ===== CONFIGURAÇÕES DE FLAGS =====
flags:
  # Flag para testes unitários
  unit:
    # Cobertura mínima para testes unitários
    target: 85%
    # Se deve falhar se não atingir o target
    threshold: 5%
  # Flag para testes de integração
  integration:
    # Cobertura mínima para testes de integração
    target: 75%
    # Se deve falhar se não atingir o target
    threshold: 10%
  # Flag para testes E2E
  e2e:
    # Cobertura mínima para testes E2E
    target: 60%
    # Se deve falhar se não atingir o target
    threshold: 15%
  # Flag para componentes
  components:
    # Cobertura mínima para componentes
    target: 90%
    # Se deve falhar se não atingir o target
    threshold: 5%

# ===== CONFIGURAÇÕES DE NOTIFICAÇÕES =====
notify:
  # Notificações por email
  email:
    # Habilitar notificações por email
    enabled: false
  # Notificações por Slack
  slack:
    # Habilitar notificações por Slack
    enabled: false
  # Notificações por webhook
  webhook:
    # Habilitar notificações por webhook
    enabled: false

# ===== CONFIGURAÇÕES DE PARALELISMO =====
parsers:
  # Parser para arquivos JavaScript/TypeScript
  javascript:
    # Habilitar parser para JS/TS
    enable_partials: true
  # Parser para arquivos Python
  python:
    # Habilitar parser para Python
    enable_partials: true

# ===== CONFIGURAÇÕES DE CACHE =====
cache:
  # Habilitar cache
  enabled: true
  # Tempo de expiração do cache (em segundos)
  expire: 3600

# ===== CONFIGURAÇÕES DE SEGURANÇA =====
security:
  # Habilitar verificações de segurança
  enabled: true
  # Verificar vulnerabilidades conhecidas
  check_vulnerabilities: true

# ===== CONFIGURAÇÕES DE PERFORMANCE =====
performance:
  # Habilitar métricas de performance
  enabled: true
  # Tempo limite para upload (em segundos)
  upload_timeout: 300

# ===== CONFIGURAÇÕES DE DEBUG =====
debug:
  # Habilitar modo debug
  enabled: false
  # Nível de log
  level: info
